# Generated by Django 3.2.8 on 2022-10-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='balance',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
