# Generated by Django 3.2.8 on 2022-10-21 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('product_name', models.CharField(default='', max_length=256)),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
