# Generated by Django 3.2.8 on 2022-10-21 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='createtime',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
